### ISSUE TITLE
Epoll error (wrong node.js version?)

### ISSUE THREAD

**Issue by hweigel** [bugsounet/MMM-NewPIR#20]
So this is happening on my RPi4 with a SR505, when running "PM2 restart mm --update-env; PM2 log" (from mm-error.log)
```
[19:28:06.212] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: The module '/home/pi/MagicMirror/modules/MMM-NewPIR/node_modules/epoll/build/Release/epoll.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
[19:28:06.219] [ERROR]  Error: The module '/home/pi/MagicMirror/modules/MMM-NewPIR/node_modules/epoll/build/Release/epoll.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/home/pi/MagicMirror/modules/MMM-NewPIR/node_modules/bindings/bindings.js:112:48)
    at module.exports._ (/home/pi/MagicMirror/modules/MMM-NewPIR/node_modules/epoll/epoll.js:7:31)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-NewPIR/node_modules/epoll/epoll.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
[19:28:33.975] [ERROR]  (node:864) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

```
Runing "npm rebuild" breaks MM, which throws an error and won't start at all.

With "npm install" the MM works, but throws false positives (movement detected when nothing is moving, tested it by looking at the screen sitting in an empty room with VNC) and false negatives (not detecting when I'm actually moving in front of the screen).

**Comment by hweigel** [comment]
FWIW, switched to MMM-AssistantMK2 with addons, but the PIR module doesn't want to work there either (and yes, I tried two different SR505 and a SR501). Anyhoo, closing this ticket, since the code's been deprecated today.
