### ISSUE TITLE
sensor problem

### ISSUE THREAD

**Issue by pakal41** [bugsounet/MMM-NewPIR#9]
hello,
I have a problem with the screen turning off but not turning on again I unplug and reconnect the PIR and the screen turns on?
here is my config
./run-start.sh "debug"
[16:43:54.193] [LOG]    Starting node_helper for module MMM-NewPIR
[16:43:54.194] [LOG]    Connecting socket for: newsfeed
[16:43:54.195] [LOG]    Starting module: newsfeed
[16:43:54.196] [LOG]    Sockets connected & modules started ...
[16:43:54.343] [LOG]    Whoops! There was an uncaught exception...
[16:43:54.344] [ERROR]  Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1413:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
[16:43:54.355] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[16:43:54.355] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[16:43:54.361] [LOG]    Launching application.

config
 module: 'MMM-NewPIR',
  position: 'top_left',
  config: {
    useSensor: true,
    sensorPin: 21,
    delay: 2* 60 * 1000,
    turnOffDisplay: true,
    ecoMode: true,
    governor: "",
    debug: false

**Comment by bugsounet** [comment]
> I have a problem with the screen turning off but not turning on again I unplug and reconnect the PIR and the screen turns on?

Sorry for my late response. 
Can you turn `debug` to `true`
and give me log please ?

> [16:43:54.344] [ERROR] Error: listen EADDRINUSE: address already in use 127.0.0.1:8080

mean you have another MagicMagic app launch (you have launch it 2 times)
to stop MagicMirror if you use pm2 program
in your terminal:
```sh 
pm2 stop all
```
start it manually for this test by:
```
cd ~/MagicMirror
npm start
```
you can now give the log like this:
```
[03:12:53.496] [LOG] [NewPIR] Initialize Complete.
[03:12:53.764] [LOG] [NewPIR] Display -- Actual: true - Wanted: true
[03:13:49.812] [LOG] [NewPIR] Sensor read value: 1
```
if sensor detect your self ->  it read value 1
if sensor detect no one -> it read value 0

some sensors need reverse value.
maybe it's you case (I can code it)
can you confirm ?

**Comment by pakal41** [comment]
yes , it works, pm2 stop,
 enough to solve my problem
 thank you for taking the time to read me
